feat: add apkanalyzer
appium/appium-doctor pull request #116
Opened 2021-01-16 23:03 UTC by KazuCocoa

```
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
info AppiumDoctor    Checking adb, android, emulator, apksigner.jar, apkanalyzer
info AppiumDoctor      'adb' is in /Users/kazuaki/Library/Android/sdk/platform-tools/adb
info AppiumDoctor      'android' is in /Users/kazuaki/Library/Android/sdk/tools/android
info AppiumDoctor      'emulator' is in /Users/kazuaki/Library/Android/sdk/emulator/emulator
info AppiumDoctor      'apkanalyzer' is in /Users/kazuaki/Library/Android/sdk/cmdline-tools/latest/bin/apkanalyzer
```

2021-01-17 08:11 UTC, mykola-mokhnach requested changes
I assume on Windows the script has .bat extension

2021-01-18 00:04 UTC, KazuCocoa commented
let me check

2021-01-19 19:48 UTC, KazuCocoa commented
<img width="192" alt="image" src="https://user-images.githubusercontent.com/5511591/105085146-b3274e00-5ada-11eb-9e86-26f37ea080a7.png">

2021-01-19 21:02 UTC, mykola-mokhnach commented on lib/android.js
> +    this.tools = ['adb', 'android', 'emulator', system.isWindows() ? 'apkanalyzer.bat' : 'apkanalyzer'];
```
`apkanalyzer${system.isWindows() ? '.bat' : ''}`
```

2021-01-19 21:02 UTC, mykola-mokhnach approved these changes

2021-01-20 00:20 UTC, merged